---
- name: deploy jupiter website
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: update ec2 instance
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: install apache server
      dnf:
        name: httpd
        state: latest

    - name: change directory to the html directory
      shell: cd /var/www/html

    - name: download web files from github
      get_url:
        url: https://github.com/azeezsalu/jupiter/archive/refs/heads/main.zip
        dest: /var/www/html/main.zip

    - name: unzip the zip folder
      ansible.builtin.unarchive:
        src: /var/www/html/main.zip
        dest: /var/www/html
        remote_src: yes

    - name: copy web files from the jupiter-main directory to the html directory
      ansible.builtin.command:
        cmd: cp -r /var/www/html/jupiter-main/* /var/www/html/
        args:
          chdir: /var/www/html
        creates: /var/www/html/index.html  # Assuming index.html exists in jupiter-main

    - name: remove the jupiter-main directory
      file:
        path: /var/www/html/jupiter-main
        state: absent

    - name: remove the main.zip file
      file:
        path: /var/www/html/main.zip
        state: absent

    - name: start apache server, if not started
      ansible.builtin.service:
        enabled: yes
        name: httpd
        state: started
