---
- name: Install Nginx and Deploy 2048 Game
  hosts: all
  become: yes
  tasks:
    - name: Install required packages using dnf
      dnf:
        name:
          - nginx
          - zip
          - curl
        state: present
      become: yes


    - name: Update apt cache
      dnf:
        name: '*'
        state: present
      become: yes

    - name: Install required packages
      dnf:
        name:
          - nginx
          - zip
          - curl
        state: present
      become: yes

    - name: Configure Nginx
      lineinfile:
        path: /etc/nginx/nginx.conf
        line: 'daemon off;'
      become: yes

    - name: Download and deploy 2048 game
      shell: |
        cd /var/www/html/
        curl -o master.zip -L https://codeload.github.com/gabrielecirulli/2048/zip/master
        unzip -o master.zip
        mv 2048-master/* .
        rm -rf 2048-master master.zip
      become: yes
      args:
        executable: /bin/bash

    - name: Ensure Nginx service is enabled and running
      systemd:
        name: nginx
        enabled: yes
        state: started
      become: yes
