---
- name: Install Nginx and Deploy 2048 Game
  hosts: all
  become: yes
  tasks:
    - name: Check Python version
      command: python --version
      register: python_version
      changed_when: false
      ignore_errors: yes

    - name: Install required packages
      yum:
        name:
          - nginx
          - zip
          - curl
        state: present
      become: yes
      when: "'Python 2.7' in python_version.stderr"

    - name: Install required packages using dnf (Python 3)
      dnf:
        name:
          - nginx
          - zip
          - curl
        state: present
      become: yes
      when: "'Python 2.7' not in python_version.stderr"

    - name: Configure Nginx
      lineinfile:
        path: /var/www/html/
        line: 'daemon off;'
      become: yes

    - name: Download and deploy 2048 game
      shell: |
        cd /var/www/html/
        curl -o master.zip -L https://codeload.github.com/gabrielecirulli/2048/zip/master
        unzip -o master.zip
        mv 2048-master/* .
        rm -rf 2048-master master.zip
      become: yes
      args:
        executable: /bin/bash

    - name: Ensure Nginx service is enabled and running
      systemd:
        name: nginx
        enabled: yes
        state: started
      become: yes

