---
- name: Install Nginx and deploy 2048 game
  hosts: all
  become: yes  # This will run the tasks as sudo

  tasks:
    - name: Install required packages (Nginx, zip, curl)
      dnf:
        name:
          - nginx
          - zip
          - curl
        state: present
      become: yes
   
    - name: Configure Nginx
      lineinfile:
        path: /etc/nginx/nginx.conf
        line: "daemon off;"
      become: yes

    - name: Download and deploy 2048 game
      shell: |
        curl -o /var/www/html/master.zip -L https://codeload.github.com/gabrielecirulli/2048/zip/master
        cd /var/www/html/ && unzip master.zip && mv 2048-master/* . && rm -rf 2048-master master.zip
      become: yes

    - name: Open port 80 (HTTP) in the firewall
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      become: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      become: yes

    # ... (rest of your playbook)
