---
- name: Install Nginx and deploy 2048 game
  hosts: all
  become: yes  # This will run the tasks as sudo

  tasks:
    - name: Install required packages (Nginx, zip, curl)
      package:
        name:
          - nginx
          - zip
          - curl
        state: present
      become: yes

    - name: Configure Nginx
      lineinfile:
        path: /etc/nginx/nginx.conf
        line: "daemon off;"
      become: yes

    - name: Download and deploy 2048 game
      get_url:
        url: https://codeload.github.com/gabrielecirulli/2048/zip/master
        dest: /tmp/2048.zip
      become: yes

    - name: Extract 2048 game
      unarchive:
        src: /tmp/2048.zip
        dest: /var/www/html/
        remote_src: yes
      become: yes

    - name: Set correct ownership and permissions
      file:
        path: /var/www/html/
        owner: nginx
        group: nginx
        recurse: yes
      become: yes

    - name: Open port 80 (HTTP) in the firewall
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      become: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      become: yes
