---
- name: Install and configure Apache HTTP server
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      command: yum update -y

    - name: Install Apache HTTP Server
      command: yum install -y httpd

    - name: Change directory
      command: cd /var/www/html

    - name: Download Jupiter repository
      command: wget https://github.com/azeezsalu/jupiter/archive/refs/heads/main.zip

    - name: Unzip Jupiter repository
      command: unzip main.zip
      args:
        chdir: /var/www/html
      when: not unzip_check.stat.exists

    - name: Check if Jupiter directory exists
      stat:
        path: /var/www/html/jupiter-main
      register: unzip_check

    - name: Copy files to web directory
      command: cp -r /var/www/html/jupiter-main/* /var/www/html/
      args:
        chdir: /var/www/html
      when: unzip_check.stat.exists

    - name: Remove temporary files
      file:
        path: "/var/www/html/{{ item }}"
        state: absent
      loop:
        - jupiter-main
        - main.zip

    - name: Enable Apache HTTPd
      command: systemctl enable httpd

    - name: Start Apache HTTPd
      command: systemctl start httpd
