---
- name: Install and configure Apache HTTP server
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      dnf:
        name: '*'
        state: latest
      become: yes

    - name: Install Apache HTTP Server
      dnf:
        name: httpd
        state: present
      become: yes

    - name: Download Jupiter repository
      get_url:
        url: https://github.com/azeezsalu/jupiter/archive/refs/heads/main.zip
        dest: /tmp/main.zip
      become: yes

    - name: Unzip Jupiter repository
      unarchive:
        src: /tmp/main.zip
        dest: /var/www/html
        remote_src: yes
        extra_opts: -q
      become: yes

    - name: Move files to web directory
      command: mv /var/www/html/jupiter-main/* /var/www/html/
      become: yes

    - name: Remove temporary files
      command: rm -rf /var/www/html/jupiter-main /tmp/main.zip
      become: yes

    - name: Enable Apache HTTPd
      systemd:
        name: httpd
        enabled: yes
      become: yes

    - name: Start Apache HTTPd
      systemd:
        name: httpd
        state: started
      become: yes
