---
- name: Install and configure Apache HTTP server
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      dnf:
        name: '*'
        state: latest

    - name: Install Apache HTTP Server
      dnf:
        name: httpd
        state: present

    - name: Change directory
      ansible.builtin.command:
        cmd: cd /var/www/html

    - name: Download Jupiter repository
      ansible.builtin.get_url:
        url: https://github.com/azeezsalu/jupiter/archive/refs/heads/main.zip
        dest: /var/www/html/main.zip

    - name: Unzip Jupiter repository
      ansible.builtin.unarchive:
        src: /var/www/html/main.zip
        dest: /var/www/html
        remote_src: yes
        creates: /var/www/html/jupiter-main

    - name: Copy files to web directory
      ansible.builtin.shell:
        cmd: cp -r /var/www/html/jupiter-main/* /var/www/html/
      when: "'/var/www/html/jupiter-main/' is exists"

    - name: Remove temporary files
      ansible.builtin.file:
        path: "/var/www/html/{{ item }}"
        state: absent
      loop:
        - jupiter-main
        - main.zip

    - name: Enable Apache HTTPd
      systemd:
        name: httpd
        enabled: yes

    - name: Start Apache HTTPd
      systemd:
        name: httpd
        state: started
