---
- name: deploy jupiter website
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: update ec2 instance
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: install apache server
      dnf:
        name: httpd
        state: latest

    - name: Create the /var/www/html directory if it doesn't exist
      ansible.builtin.file:
        path: /var/www/html
        state: directory

    - name: download web files from github
      get_url:
        url: https://codeload.github.com/gabrielecirulli/2048/zip/master
        dest: /var/www/html/master.zip

    - name: unzip the zip folder
      ansible.builtin.unarchive:
        src: /var/www/html/master.zip
        dest: /var/www/html
        remote_src: yes

    - name: remove the master.zip file
      ansible.builtin.file:
        path: /var/www/html/master.zip
        state: absent

    - name: start apache server, if not started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
